### ISSUE TITLE
Error creating connection pool in Cassandra

### ISSUE THREAD

**Issue by AnderUstarroz** [docker-library/official-images#2144]
I am running a web app with python **3.5.2**, uWSGI **2.0.11.2**, cassandra-driver **3.6.0** and cassandra **3.7**.

I have built a Cassandra cluster with 3 nodes, Node 1 (**172.17.0.4**), Node 2 (**172.17.0.5**), Node 3 (**172.17.0.6**)

The docker containers are running with the following configuration:

`docker run --name Node1 -d cassandra:3.7`
`docker run --name Node2 --link Node1:seed -d cassandra:3.7`
`docker run --name Node3 --link Node1:seed -d cassandra:3.7`
`docker run --name app Node1:node1 --link Node2:node2 --link Node3:node3 --link app:latest`

But anytime I am trying to connect to my app, I am getting the following errors:
```
Respawned uWSGI worker 2 (new pid: 90)
mapping worker 2 to CPUs: 3 4 5
2016-09-14 21:00:47,434 WARNI [cassandra.cluster][Thread-2] Failed to create connection pool for new host 172.17.0.4:
Traceback (most recent call last):
    File "cassandra/cluster.py", line 2232, in cassandra.cluster.Session.add_or_renew_pool.run_add_or_renew_pool (cassandra/cluster.c:38826)
    File "cassandra/pool.py", line 328, in cassandra.pool.HostConnection.__init__ (cassandra/pool.c:6243)
    File "cassandra/cluster.py", line 1107, in cassandra.cluster.Cluster.connection_factory (cassandra/cluster.c:14943)
    File "cassandra/connection.py", line 330, in cassandra.connection.Connection.factory (cassandra/connection.c:5766)
cassandra.OperationTimedOut: errors=Timed out creating connection (5 seconds), last_host=None
2016-09-14 21:00:47,437 WARNI [cassandra.cluster][Thread-1] Failed to create connection pool for new host 172.17.0.6:
Traceback (most recent call last):
    File "cassandra/cluster.py", line 2232, in cassandra.cluster.Session.add_or_renew_pool.run_add_or_renew_pool (cassandra/cluster.c:38826)
    File "cassandra/pool.py", line 328, in cassandra.pool.HostConnection.__init__ (cassandra/pool.c:6243)
    File "cassandra/cluster.py", line 1107, in cassandra.cluster.Cluster.connection_factory (cassandra/cluster.c:14943)
    File "cassandra/connection.py", line 330, in cassandra.connection.Connection.factory (cassandra/connection.c:5766)
cassandra.OperationTimedOut: errors=Timed out creating connection (5 seconds), last_host=None
...The work of process 19 is done. Seeya!
worker 7 killed successfully (pid: 19)

```
Am I doing something wrong? I have posted more detailed information about this issue [here](http://stackoverflow.com/questions/39499996/cassandra-failed-to-create-connection-pool-for-new-host).

**Comment by yosifkit** [comment]
Are you sure the three nodes are even in a cluster?  The entrypoint script will only set seeds for you if you [name the link `cassandra`](https://github.com/docker-library/cassandra/blob/ef66ec669d3930aea018f74dc58f5bd2ef5df880/docker-entrypoint.sh#L30-L32).

```console
$ # I had to set memory limits or I ran out of space for the 3rd node
$ docker run --name some-cassandra -d -m 2g -e MAX_HEAP_SIZE=1G -e HEAP_NEWSIZE=500M cassandra
$ docker run --name some-cassandra2 -d --link some-cassandra:cassandra -m 2g -e MAX_HEAP_SIZE=1G -e HEAP_NEWSIZE=500M cassandra
$ docker run --name some-cassandra3 -d --link some-cassandra:cassandra -m 2g -e MAX_HEAP_SIZE=1G -e HEAP_NEWSIZE=500M cassandra
```

**Comment by AnderUstarroz** [comment]
Hi @yosifkit I was pretty sure they were part of the same cluster, when I added the tables to the first node, the tables automatically appeared on nodes 2 and 3. Nonetheless I have used your configuration just to rule out the issue. Still getting the same errors though

```
2016-09-15 21:00:06,084 WARNI [cassandra.cluster][Thread-2] Failed to create connection pool for new host 172.17.0.5:
Traceback (most recent call last):
  File "cassandra/cluster.py", line 2232, in cassandra.cluster.Session.add_or_renew_pool.run_add_or_renew_pool (cassandra/cluster.c:38826)
  File "cassandra/pool.py", line 328, in cassandra.pool.HostConnection.__init__ (cassandra/pool.c:6243)
  File "cassandra/cluster.py", line 1107, in cassandra.cluster.Cluster.connection_factory (cassandra/cluster.c:14943)
  File "cassandra/connection.py", line 330, in cassandra.connection.Connection.factory (cassandra/connection.c:5766)
cassandra.OperationTimedOut: errors=Timed out creating connection (5 seconds), last_host=None
2016-09-15 21:00:06,088 WARNI [cassandra.cluster][Thread-1] Failed to create connection pool for new host 172.17.0.4:
Traceback (most recent call last):
  File "cassandra/cluster.py", line 2232, in cassandra.cluster.Session.add_or_renew_pool.run_add_or_renew_pool (cassandra/cluster.c:38826)
  File "cassandra/pool.py", line 328, in cassandra.pool.HostConnection.__init__ (cassandra/pool.c:6243)
  File "cassandra/cluster.py", line 1107, in cassandra.cluster.Cluster.connection_factory (cassandra/cluster.c:14943)
  File "cassandra/connection.py", line 330, in cassandra.connection.Connection.factory (cassandra/connection.c:5766)
cassandra.OperationTimedOut: errors=Timed out creating connection (5 seconds), last_host=None
[pid: 16|app: 0|req: 1/1] 118.93.224.165 () {44 vars in 978 bytes} [Thu Sep 15 21:00:06 2016] GET / => generated 17572 bytes in 239 msecs (HTTP/2.0 200) 2 headers in 82 bytes (1 switches on core 0)
```

**Comment by AnderUstarroz** [comment]
uWSGI Preforking was causing undesired effects on the connections  to the  Cassandra nodes. I have fixed this issue using the param **lazy-apps= true** in uWSGI configuration.
