### ISSUE TITLE
Jenkins has failed to create a temporary file in /tmp

### ISSUE THREAD

**Issue by joshuacox** [docker-library/official-images#2583]
Given a new pull 

```
1/24/2017 10:09:59 PMRunning from: /usr/share/jenkins/jenkins.war
1/24/2017 10:09:59 PMwebroot: EnvVars.masterEnvVars.get("JENKINS_HOME")
1/24/2017 10:09:59 PMException in thread "main" java.io.IOException: Jenkins has failed to create a temporary file in /tmp
1/24/2017 10:09:59 PM	at Main.extractFromJar(Main.java:368)
1/24/2017 10:09:59 PM	at Main._main(Main.java:210)
1/24/2017 10:09:59 PM	at Main.main(Main.java:112)
1/24/2017 10:09:59 PMCaused by: java.io.IOException: Permission denied
1/24/2017 10:09:59 PM	at java.io.UnixFileSystem.createFileExclusively(Native Method)
1/24/2017 10:09:59 PM	at java.io.File.createTempFile(File.java:2024)
1/24/2017 10:09:59 PM	at Main.extractFromJar(Main.java:365)
1/24/2017 10:09:59 PM	... 2 more
```

This is over NFS.  Here is what the resulting directory looks like:
```
# ls -lhn JENKINS/
total 8.0K
-rw-r--r-- 1 1000 1000 3.5K Jan 24 22:13 copy_reference_file.log
drwxr-xr-x 2 1000 1000   48 Jan 24 21:47 init.groovy.d
drwxr-xr-x 2 1000 1000 4.0K Jan 24 21:48 plugins
```

I can also make the tmp dir and mod it to 777:

```
ls -lhn JENKINS/
total 8.0K
-rw-r--r-- 1 1000 1000 3.6K Jan 24 22:14 copy_reference_file.log
drwxr-xr-x 2 1000 1000   48 Jan 24 21:47 init.groovy.d
drwxr-xr-x 2 1000 1000 4.0K Jan 24 21:48 plugins
drwxrwxrwx 2    0    0    6 Jan 24 22:14 tmp
```

same result

**Comment by tianon** [comment]
I think this was probably intended to be filed over at https://github.com/jenkinsci/docker/issues?

**Comment by joshuacox** [comment]
yep closing here, sorry
