### ISSUE TITLE
Issue in sentry image

### ISSUE THREAD

**Issue by Kaleesastha** [docker-library/official-images#817]
I got an error while executing the official sentry image in my local message and the logs are given below :-1: 
sudo docker logs -f sentry-instance
Traceback (most recent call last):
  File "/usr/local/bin/sentry", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python2.7/site-packages/sentry/utils/runner.py", line 435, in main
    initializer=initialize_app,
  File "/usr/local/lib/python2.7/site-packages/logan/runner.py", line 191, in run_app
    configure_app(config_path=config_path, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/logan/runner.py", line 104, in configure_app
    raise ValueError("Configuration file does not exist at %r" % (config_path,))
ValueError: Configuration file does not exist at '/home/user/.sentry/sentry.conf.py'

Please help me to resolve this issue ...

**Comment by tianon** [comment]
https://github.com/docker-library/sentry/issues would be a more appropriate place to report this, but it's actually already reported in https://github.com/docker-library/sentry/issues/11.
